{
  imports = [
    ./cmp.nix
    ./conform.nix
    ./dap.nix
    ./lint.nix
    ./lsp.nix
    ./lz-n.nix
    ./markdown-preview.nix
    ./mini.nix
    ./muren.nix
    ./navic.nix
    ./neogen.nix
    ./neogit.nix
    ./obsidian.nix
    ./project.nix
    ./tagbar.nix
    ./telescope.nix
    ./treesitter.nix
    ./trouble.nix
  ];
}
